development:
 secret_key_base: <%= ENV["SECRET_KEY_DEV"] %>

test:
 secret_key_base: <%= ENV["SECRET_KEY_TEST"] %>

production:
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
